/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClinicRouteImport } from './routes/_clinic'
import { Route as ClinicIndexRouteImport } from './routes/_clinic/index'
import { Route as ClinicAssistantsRouteImport } from './routes/_clinic/assistants'
import { Route as ClinicCareRouteImport } from './routes/_clinic/care'
import { Route as ClinicRecruitRouteImport } from './routes/_clinic/recruit'
import { Route as ClinicSupportRouteImport } from './routes/_clinic/support'
import { Route as ClinicVisitRouteImport } from './routes/_clinic/visit'

const ClinicRoute = ClinicRouteImport.update({
  id: '/_clinic',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicIndexRoute = ClinicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClinicRoute,
} as any)
const ClinicAssistantsRoute = ClinicAssistantsRouteImport.update({
  id: '/assistants',
  path: '/assistants',
  getParentRoute: () => ClinicRoute,
} as any)
const ClinicCareRoute = ClinicCareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => ClinicRoute,
} as any)
const ClinicRecruitRoute = ClinicRecruitRouteImport.update({
  id: '/recruit',
  path: '/recruit',
  getParentRoute: () => ClinicRoute,
} as any)
const ClinicSupportRoute = ClinicSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => ClinicRoute,
} as any)
const ClinicVisitRoute = ClinicVisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => ClinicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ClinicIndexRoute
  '/assistants': typeof ClinicAssistantsRoute
  '/care': typeof ClinicCareRoute
  '/recruit': typeof ClinicRecruitRoute
  '/support': typeof ClinicSupportRoute
  '/visit': typeof ClinicVisitRoute
}
export interface FileRoutesByTo {
  '/assistants': typeof ClinicAssistantsRoute
  '/care': typeof ClinicCareRoute
  '/recruit': typeof ClinicRecruitRoute
  '/support': typeof ClinicSupportRoute
  '/visit': typeof ClinicVisitRoute
  '/': typeof ClinicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_clinic': typeof ClinicRouteWithChildren
  '/_clinic/assistants': typeof ClinicAssistantsRoute
  '/_clinic/care': typeof ClinicCareRoute
  '/_clinic/recruit': typeof ClinicRecruitRoute
  '/_clinic/support': typeof ClinicSupportRoute
  '/_clinic/visit': typeof ClinicVisitRoute
  '/_clinic/': typeof ClinicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/assistants' | '/care' | '/recruit' | '/support' | '/visit'
  fileRoutesByTo: FileRoutesByTo
  to: '/assistants' | '/care' | '/recruit' | '/support' | '/visit' | '/'
  id:
    | '__root__'
    | '/_clinic'
    | '/_clinic/assistants'
    | '/_clinic/care'
    | '/_clinic/recruit'
    | '/_clinic/support'
    | '/_clinic/visit'
    | '/_clinic/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ClinicRoute: typeof ClinicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_clinic': {
      id: '/_clinic'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ClinicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_clinic/': {
      id: '/_clinic/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ClinicIndexRouteImport
      parentRoute: typeof ClinicRoute
    }
    '/_clinic/assistants': {
      id: '/_clinic/assistants'
      path: '/assistants'
      fullPath: '/assistants'
      preLoaderRoute: typeof ClinicAssistantsRouteImport
      parentRoute: typeof ClinicRoute
    }
    '/_clinic/care': {
      id: '/_clinic/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof ClinicCareRouteImport
      parentRoute: typeof ClinicRoute
    }
    '/_clinic/recruit': {
      id: '/_clinic/recruit'
      path: '/recruit'
      fullPath: '/recruit'
      preLoaderRoute: typeof ClinicRecruitRouteImport
      parentRoute: typeof ClinicRoute
    }
    '/_clinic/support': {
      id: '/_clinic/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof ClinicSupportRouteImport
      parentRoute: typeof ClinicRoute
    }
    '/_clinic/visit': {
      id: '/_clinic/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof ClinicVisitRouteImport
      parentRoute: typeof ClinicRoute
    }
  }
}

interface ClinicRouteChildren {
  ClinicAssistantsRoute: typeof ClinicAssistantsRoute
  ClinicCareRoute: typeof ClinicCareRoute
  ClinicRecruitRoute: typeof ClinicRecruitRoute
  ClinicSupportRoute: typeof ClinicSupportRoute
  ClinicVisitRoute: typeof ClinicVisitRoute
  ClinicIndexRoute: typeof ClinicIndexRoute
}

const ClinicRouteChildren: ClinicRouteChildren = {
  ClinicAssistantsRoute: ClinicAssistantsRoute,
  ClinicCareRoute: ClinicCareRoute,
  ClinicRecruitRoute: ClinicRecruitRoute,
  ClinicSupportRoute: ClinicSupportRoute,
  ClinicVisitRoute: ClinicVisitRoute,
  ClinicIndexRoute: ClinicIndexRoute,
}

const ClinicRouteWithChildren =
  ClinicRoute._addFileChildren(ClinicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ClinicRoute: ClinicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
